trees:
  - path: /
    tree: tiled.catalog:from_uri
    args:
      uri: sqlite+aiosqlite:///catalog.db
      readable_storage:
        -  D:\microscopedata
      adapters_by_mimetype:
        application/x-emd: custom:EMDAdapter


